version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: mansysdb
      DB_USERNAME: mansys
      DB_PASSWORD: DEzeY6cRt0H4ZcJV
      JWT_SECRET: joJfUJmgkM2aWyLqj48L7MAvO2LpM7b3e1Me9rbKQYhvyqkUOnyJAUL6a4YCxPxh
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: mansys
      MYSQL_PASSWORD: DEzeY6cRt0H4ZcJV
      MYSQL_DATABASE: mansysdb
      MYSQL_RANDOM_ROOT_PASSWORD: 1