version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: db
      DB_PORT: 27017
      DB_DATABASE: mansysdb
      DB_USERNAME: mansys
      DB_PASSWORD: DEzeY6cRt0H4ZcJV
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mansys
      MONGO_INITDB_ROOT_PASSWORD: DEzeY6cRt0H4ZcJV
      MONGO_INITDB_DATABASE: mansysdb