#!/usr/bin/env bash

if [[ ! -d "/var/www/html/vendor" ]]; then
    composer install
fi

if [[ ! -d "/var/www/html/node_modules" ]]; then
    npm install
fi

if [[ ! -f "/var/www/html/.env" ]]; then
    cp /var/www/html/.env.example /var/www/html/.env
fi

docker-php-entrypoint "$@"

